name: Pull request verification

on: [pull_request]

jobs:
  build:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Run tests
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go test ./...

      - run: make fmt

      - run: make assets

      - run: make build
